# Generated by Django 5.2.16 on 2026-07-21 00:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-created_at'], 'verbose_name': "Journal d'Activité Utilisateur", 'verbose_name_plural': "Journaux d'Activité Utilisateur"},
        ),
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-created_at'], 'verbose_name': "Journal d'Audit (Global)", 'verbose_name_plural': "Journaux d'Audit (Global)"},
        ),
        migrations.AlterModelOptions(
            name='systemlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Journal Système (Technique)', 'verbose_name_plural': 'Journaux Système (Technique)'},
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='created_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de création'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='description',
            field=models.TextField(verbose_name="Description de l'activité"),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID unique (UUID)'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Est supprimé (Soft Delete)'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Visible publiquement'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date de dernière modification'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Mis à jour par'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='updated_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de modification'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Action effectuée'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Acteur'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='changes',
            field=models.JSONField(default=dict, verbose_name='Détail des modifications'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='created_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de création'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='entity_id',
            field=models.UUIDField(blank=True, null=True, verbose_name="ID de l'entité"),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='entity_type',
            field=models.CharField(max_length=100, verbose_name="Type d'entité affectée"),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID unique (UUID)'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Est supprimé (Soft Delete)'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date de dernière modification'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Mis à jour par'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='updated_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de modification'),
        ),
        migrations.AlterField(
            model_name='systemlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='systemlog',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='systemlog',
            name='created_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de création'),
        ),
        migrations.AlterField(
            model_name='systemlog',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression'),
        ),
        migrations.AlterField(
            model_name='systemlog',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID unique (UUID)'),
        ),
        migrations.AlterField(
            model_name='systemlog',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Est supprimé (Soft Delete)'),
        ),
        migrations.AlterField(
            model_name='systemlog',
            name='level',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Niveau (Gravité)'),
        ),
        migrations.AlterField(
            model_name='systemlog',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='systemlog',
            name='source',
            field=models.CharField(max_length=100, verbose_name='Source / Module'),
        ),
        migrations.AlterField(
            model_name='systemlog',
            name='traceback',
            field=models.TextField(blank=True, verbose_name='Traceback (Stack trace)'),
        ),
        migrations.AlterField(
            model_name='systemlog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date de dernière modification'),
        ),
        migrations.AlterField(
            model_name='systemlog',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Mis à jour par'),
        ),
        migrations.AlterField(
            model_name='systemlog',
            name='updated_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de modification'),
        ),
    ]
