# Generated by Django 5.2.16 on 2026-07-15 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Montant payé (FCFA)')),
                ('payment_method', models.CharField(choices=[('card', 'Carte Bancaire (Visa/Mastercard)'), ('wave', 'Wave'), ('orange_money', 'Orange Money')], max_length=20, verbose_name='Moyen de paiement')),
                ('transaction_id', models.CharField(max_length=100, unique=True, verbose_name='ID de transaction')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('completed', 'Réussi'), ('failed', 'Échoué')], default='pending', max_length=15, verbose_name='Statut du paiement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-created_at'],
            },
        ),
    ]
