# Generated by Django 5.2.16 on 2026-07-21 00:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('updated_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('guests', models.PositiveIntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('REQUESTED', 'Demandé'), ('UNDER_REVIEW', 'En cours de révision (SuperAdmin)'), ('SENT_TO_OWNER', 'Transmis au Propriétaire'), ('OWNER_ACCEPTED', 'Accepté par le Propriétaire'), ('OWNER_DECLINED', 'Refusé par le Propriétaire'), ('PAYMENT_PENDING', 'En attente de paiement'), ('PAID', 'Payé'), ('CONFIRMED', 'Confirmé'), ('CHECKIN', 'Check-in'), ('CHECKOUT', 'Check-out'), ('COMPLETED', 'Terminé'), ('CANCELLED', 'Annulé')], db_index=True, default='CONFIRMED', max_length=20)),
                ('confirmation_code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='properties.property')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reservations_reservation',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReservationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('updated_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('action', models.CharField(max_length=255)),
                ('details', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='reservations.reservation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reservations_history',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReservationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('updated_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('guests', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('REQUESTED', 'Demandé'), ('UNDER_REVIEW', 'En cours de révision (SuperAdmin)'), ('SENT_TO_OWNER', 'Transmis au Propriétaire'), ('OWNER_ACCEPTED', 'Accepté par le Propriétaire'), ('OWNER_DECLINED', 'Refusé par le Propriétaire'), ('PAYMENT_PENDING', 'En attente de paiement'), ('PAID', 'Payé'), ('CONFIRMED', 'Confirmé'), ('CHECKIN', 'Check-in'), ('CHECKOUT', 'Check-out'), ('COMPLETED', 'Terminé'), ('CANCELLED', 'Annulé')], db_index=True, default='REQUESTED', max_length=20)),
                ('special_requests', models.TextField(blank=True)),
                ('superadmin_notes', models.TextField(blank=True, help_text='Notes internes pour le SuperAdmin')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservation_requests', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservation_requests', to='properties.property')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reservations_request',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reservation', to='reservations.reservationrequest'),
        ),
        migrations.CreateModel(
            name='ReservationStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('updated_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('old_status', models.CharField(choices=[('REQUESTED', 'Demandé'), ('UNDER_REVIEW', 'En cours de révision (SuperAdmin)'), ('SENT_TO_OWNER', 'Transmis au Propriétaire'), ('OWNER_ACCEPTED', 'Accepté par le Propriétaire'), ('OWNER_DECLINED', 'Refusé par le Propriétaire'), ('PAYMENT_PENDING', 'En attente de paiement'), ('PAID', 'Payé'), ('CONFIRMED', 'Confirmé'), ('CHECKIN', 'Check-in'), ('CHECKOUT', 'Check-out'), ('COMPLETED', 'Terminé'), ('CANCELLED', 'Annulé')], max_length=20)),
                ('new_status', models.CharField(choices=[('REQUESTED', 'Demandé'), ('UNDER_REVIEW', 'En cours de révision (SuperAdmin)'), ('SENT_TO_OWNER', 'Transmis au Propriétaire'), ('OWNER_ACCEPTED', 'Accepté par le Propriétaire'), ('OWNER_DECLINED', 'Refusé par le Propriétaire'), ('PAYMENT_PENDING', 'En attente de paiement'), ('PAID', 'Payé'), ('CONFIRMED', 'Confirmé'), ('CHECKIN', 'Check-in'), ('CHECKOUT', 'Check-out'), ('COMPLETED', 'Terminé'), ('CANCELLED', 'Annulé')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='reservations.reservationrequest')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reservations_status_history',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='reservationrequest',
            constraint=models.CheckConstraint(condition=models.Q(('check_out__gt', models.F('check_in'))), name='check_dates_validity'),
        ),
    ]
