# Generated by Django 5.2.16 on 2026-07-21 00:58

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_property_options_alter_propertyamenity_options_and_more'),
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Réservation', 'verbose_name_plural': 'Réservations'},
        ),
        migrations.AlterModelOptions(
            name='reservationhistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Historique de Réservation', 'verbose_name_plural': 'Historiques de Réservations'},
        ),
        migrations.AlterModelOptions(
            name='reservationrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Demande de Réservation', 'verbose_name_plural': 'Demandes de Réservation'},
        ),
        migrations.AlterModelOptions(
            name='reservationstatushistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Historique Statut Demande', 'verbose_name_plural': 'Historiques Statuts Demandes'},
        ),
        migrations.AlterField(
            model_name='reservation',
            name='check_in',
            field=models.DateField(verbose_name="Date d'arrivée"),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='check_out',
            field=models.DateField(verbose_name='Date de départ'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='confirmation_code',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Code de confirmation'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='created_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de création'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='guests',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Nombre de voyageurs'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID unique (UUID)'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Est supprimé (Soft Delete)'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='properties.property', verbose_name='Propriété'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reservation', to='reservations.reservationrequest', verbose_name='Demande liée'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Demandé'), ('UNDER_REVIEW', 'En cours de révision (SuperAdmin)'), ('SENT_TO_OWNER', 'Transmis au Propriétaire'), ('OWNER_ACCEPTED', 'Accepté par le Propriétaire'), ('OWNER_DECLINED', 'Refusé par le Propriétaire'), ('PAYMENT_PENDING', 'En attente de paiement'), ('PAID', 'Payé'), ('CONFIRMED', 'Confirmé'), ('CHECKIN', 'Check-in'), ('CHECKOUT', 'Check-out'), ('COMPLETED', 'Terminé'), ('CANCELLED', 'Annulé')], db_index=True, default='CONFIRMED', max_length=20, verbose_name='Statut de la réservation'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Prix total'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date de dernière modification'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Mis à jour par'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='updated_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de modification'),
        ),
        migrations.AlterField(
            model_name='reservationhistory',
            name='action',
            field=models.CharField(max_length=255, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='reservationhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='reservationhistory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='reservationhistory',
            name='created_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de création'),
        ),
        migrations.AlterField(
            model_name='reservationhistory',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression'),
        ),
        migrations.AlterField(
            model_name='reservationhistory',
            name='details',
            field=models.JSONField(default=dict, verbose_name='Détails'),
        ),
        migrations.AlterField(
            model_name='reservationhistory',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID unique (UUID)'),
        ),
        migrations.AlterField(
            model_name='reservationhistory',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Est supprimé (Soft Delete)'),
        ),
        migrations.AlterField(
            model_name='reservationhistory',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='reservations.reservation', verbose_name='Réservation'),
        ),
        migrations.AlterField(
            model_name='reservationhistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date de dernière modification'),
        ),
        migrations.AlterField(
            model_name='reservationhistory',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Mis à jour par'),
        ),
        migrations.AlterField(
            model_name='reservationhistory',
            name='updated_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de modification'),
        ),
        migrations.AlterField(
            model_name='reservationrequest',
            name='check_in',
            field=models.DateField(verbose_name="Date d'arrivée"),
        ),
        migrations.AlterField(
            model_name='reservationrequest',
            name='check_out',
            field=models.DateField(verbose_name='Date de départ'),
        ),
        migrations.AlterField(
            model_name='reservationrequest',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservation_requests', to=settings.AUTH_USER_MODEL, verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='reservationrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='reservationrequest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='reservationrequest',
            name='created_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de création'),
        ),
        migrations.AlterField(
            model_name='reservationrequest',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression'),
        ),
        migrations.AlterField(
            model_name='reservationrequest',
            name='guests',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Nombre de voyageurs'),
        ),
        migrations.AlterField(
            model_name='reservationrequest',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID unique (UUID)'),
        ),
        migrations.AlterField(
            model_name='reservationrequest',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Est supprimé (Soft Delete)'),
        ),
        migrations.AlterField(
            model_name='reservationrequest',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservation_requests', to='properties.property', verbose_name='Propriété'),
        ),
        migrations.AlterField(
            model_name='reservationrequest',
            name='special_requests',
            field=models.TextField(blank=True, verbose_name='Demandes spéciales'),
        ),
        migrations.AlterField(
            model_name='reservationrequest',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Demandé'), ('UNDER_REVIEW', 'En cours de révision (SuperAdmin)'), ('SENT_TO_OWNER', 'Transmis au Propriétaire'), ('OWNER_ACCEPTED', 'Accepté par le Propriétaire'), ('OWNER_DECLINED', 'Refusé par le Propriétaire'), ('PAYMENT_PENDING', 'En attente de paiement'), ('PAID', 'Payé'), ('CONFIRMED', 'Confirmé'), ('CHECKIN', 'Check-in'), ('CHECKOUT', 'Check-out'), ('COMPLETED', 'Terminé'), ('CANCELLED', 'Annulé')], db_index=True, default='REQUESTED', max_length=20, verbose_name='Statut de la demande'),
        ),
        migrations.AlterField(
            model_name='reservationrequest',
            name='superadmin_notes',
            field=models.TextField(blank=True, help_text='Notes invisibles pour le client et le propriétaire', verbose_name='Notes internes (SuperAdmin)'),
        ),
        migrations.AlterField(
            model_name='reservationrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date de dernière modification'),
        ),
        migrations.AlterField(
            model_name='reservationrequest',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Mis à jour par'),
        ),
        migrations.AlterField(
            model_name='reservationrequest',
            name='updated_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de modification'),
        ),
        migrations.AlterField(
            model_name='reservationstatushistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='reservationstatushistory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='reservationstatushistory',
            name='created_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de création'),
        ),
        migrations.AlterField(
            model_name='reservationstatushistory',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression'),
        ),
        migrations.AlterField(
            model_name='reservationstatushistory',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID unique (UUID)'),
        ),
        migrations.AlterField(
            model_name='reservationstatushistory',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Est supprimé (Soft Delete)'),
        ),
        migrations.AlterField(
            model_name='reservationstatushistory',
            name='new_status',
            field=models.CharField(choices=[('REQUESTED', 'Demandé'), ('UNDER_REVIEW', 'En cours de révision (SuperAdmin)'), ('SENT_TO_OWNER', 'Transmis au Propriétaire'), ('OWNER_ACCEPTED', 'Accepté par le Propriétaire'), ('OWNER_DECLINED', 'Refusé par le Propriétaire'), ('PAYMENT_PENDING', 'En attente de paiement'), ('PAID', 'Payé'), ('CONFIRMED', 'Confirmé'), ('CHECKIN', 'Check-in'), ('CHECKOUT', 'Check-out'), ('COMPLETED', 'Terminé'), ('CANCELLED', 'Annulé')], max_length=20, verbose_name='Nouveau statut'),
        ),
        migrations.AlterField(
            model_name='reservationstatushistory',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='reservationstatushistory',
            name='old_status',
            field=models.CharField(choices=[('REQUESTED', 'Demandé'), ('UNDER_REVIEW', 'En cours de révision (SuperAdmin)'), ('SENT_TO_OWNER', 'Transmis au Propriétaire'), ('OWNER_ACCEPTED', 'Accepté par le Propriétaire'), ('OWNER_DECLINED', 'Refusé par le Propriétaire'), ('PAYMENT_PENDING', 'En attente de paiement'), ('PAID', 'Payé'), ('CONFIRMED', 'Confirmé'), ('CHECKIN', 'Check-in'), ('CHECKOUT', 'Check-out'), ('COMPLETED', 'Terminé'), ('CANCELLED', 'Annulé')], max_length=20, verbose_name='Ancien statut'),
        ),
        migrations.AlterField(
            model_name='reservationstatushistory',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='reservations.reservationrequest', verbose_name='Demande'),
        ),
        migrations.AlterField(
            model_name='reservationstatushistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date de dernière modification'),
        ),
        migrations.AlterField(
            model_name='reservationstatushistory',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Mis à jour par'),
        ),
        migrations.AlterField(
            model_name='reservationstatushistory',
            name='updated_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de modification'),
        ),
    ]
