# Generated by Django 5.2.16 on 2026-07-21 00:58

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['-created_at'], 'verbose_name': 'Adresse', 'verbose_name_plural': 'Adresses'},
        ),
        migrations.AlterModelOptions(
            name='audituser',
            options={'ordering': ['-created_at'], 'verbose_name': 'Audit Utilisateur', 'verbose_name_plural': 'Audits Utilisateurs'},
        ),
        migrations.AlterModelOptions(
            name='identitydocument',
            options={'ordering': ['-created_at'], 'verbose_name': "Pièce d'identité", 'verbose_name_plural': "Pièces d'identité"},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at'], 'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Profil Utilisateur', 'verbose_name_plural': 'Profils Utilisateurs'},
        ),
        migrations.AlterModelOptions(
            name='usersession',
            options={'ordering': ['-created_at'], 'verbose_name': 'Session Utilisateur', 'verbose_name_plural': 'Sessions Utilisateurs'},
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(max_length=100, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='address',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='address',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='address',
            name='created_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de création'),
        ),
        migrations.AlterField(
            model_name='address',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression'),
        ),
        migrations.AlterField(
            model_name='address',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID unique (UUID)'),
        ),
        migrations.AlterField(
            model_name='address',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Est par défaut'),
        ),
        migrations.AlterField(
            model_name='address',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Est supprimé (Soft Delete)'),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(max_length=20, verbose_name='Code postal'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=255, verbose_name='Rue'),
        ),
        migrations.AlterField(
            model_name='address',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date de dernière modification'),
        ),
        migrations.AlterField(
            model_name='address',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Mis à jour par'),
        ),
        migrations.AlterField(
            model_name='address',
            name='updated_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de modification'),
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='audituser',
            name='action',
            field=models.CharField(max_length=50, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='audituser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='audituser',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='audituser',
            name='created_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de création'),
        ),
        migrations.AlterField(
            model_name='audituser',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression'),
        ),
        migrations.AlterField(
            model_name='audituser',
            name='details',
            field=models.JSONField(default=dict, verbose_name='Détails supplémentaires'),
        ),
        migrations.AlterField(
            model_name='audituser',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID unique (UUID)'),
        ),
        migrations.AlterField(
            model_name='audituser',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP'),
        ),
        migrations.AlterField(
            model_name='audituser',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Est supprimé (Soft Delete)'),
        ),
        migrations.AlterField(
            model_name='audituser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date de dernière modification'),
        ),
        migrations.AlterField(
            model_name='audituser',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Mis à jour par'),
        ),
        migrations.AlterField(
            model_name='audituser',
            name='updated_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de modification'),
        ),
        migrations.AlterField(
            model_name='audituser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_trails', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='identitydocument',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='identitydocument',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='identitydocument',
            name='created_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de création'),
        ),
        migrations.AlterField(
            model_name='identitydocument',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression'),
        ),
        migrations.AlterField(
            model_name='identitydocument',
            name='document_number',
            field=models.CharField(max_length=100, verbose_name='Numéro de document'),
        ),
        migrations.AlterField(
            model_name='identitydocument',
            name='document_type',
            field=models.CharField(max_length=50, verbose_name='Type de document'),
        ),
        migrations.AlterField(
            model_name='identitydocument',
            name='file',
            field=models.FileField(upload_to='identity_documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Fichier'),
        ),
        migrations.AlterField(
            model_name='identitydocument',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID unique (UUID)'),
        ),
        migrations.AlterField(
            model_name='identitydocument',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Est supprimé (Soft Delete)'),
        ),
        migrations.AlterField(
            model_name='identitydocument',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Est vérifié'),
        ),
        migrations.AlterField(
            model_name='identitydocument',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date de dernière modification'),
        ),
        migrations.AlterField(
            model_name='identitydocument',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Mis à jour par'),
        ),
        migrations.AlterField(
            model_name='identitydocument',
            name='updated_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de modification'),
        ),
        migrations.AlterField(
            model_name='identitydocument',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_documents', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='identitydocument',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de vérification'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de création'),
        ),
        migrations.AlterField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Adresse email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID unique (UUID)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_client',
            field=models.BooleanField(default=True, verbose_name='Est un client'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Est supprimé (Soft Delete)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_owner',
            field=models.BooleanField(default=False, verbose_name='Est un propriétaire'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superadmin',
            field=models.BooleanField(default=False, verbose_name='Est SuperAdmin'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date de dernière modification'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Mis à jour par'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de modification'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de création'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID unique (UUID)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Est supprimé (Soft Delete)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Le numéro de téléphone doit être au format: '+999999999'. Jusqu'à 15 chiffres.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date de dernière modification'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Mis à jour par'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de modification'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='created_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de création'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID unique (UUID)'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Est supprimé (Soft Delete)'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='last_activity',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière activité'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='session_key',
            field=models.CharField(max_length=40, unique=True, verbose_name='Clé de session'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date de dernière modification'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Mis à jour par'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='updated_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de modification'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='User Agent'),
        ),
    ]
