# Generated by Django 5.2.16 on 2026-07-26 11:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_address_options_alter_audituser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='identitydocument',
            name='selfie_file',
            field=models.ImageField(blank=True, help_text="Photo du titulaire tenant sa pièce d'identité, pour vérification anti-fraude.", null=True, upload_to='identity_documents/selfies/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name="Selfie avec la pièce d'identité"),
        ),
        migrations.AlterField(
            model_name='identitydocument',
            name='file',
            field=models.FileField(upload_to='identity_documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name="Fichier (pièce d'identité)"),
        ),
    ]
