# Generated by Django 5.2.16 on 2026-07-26 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_identitydocument_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Propriétaire vérifié (KYC)'),
        ),
    ]
