# Generated by Django 5.2.16 on 2026-08-07 00:52

import apps.core.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='identitydocument',
            name='file_back',
            field=models.FileField(blank=True, help_text="Obligatoire pour une carte nationale d'identité (recto/verso) ; sans objet pour un passeport.", null=True, storage=apps.core.storage.PrivateFileSystemStorage(location='C:\\Users\\USER\\Videos\\Projet_DWY\\projet_dwy\\media\\private'), upload_to='identity_documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name="Fichier (pièce d'identité, verso)"),
        ),
        migrations.AlterField(
            model_name='identitydocument',
            name='file',
            field=models.FileField(storage=apps.core.storage.PrivateFileSystemStorage(location='C:\\Users\\USER\\Videos\\Projet_DWY\\projet_dwy\\media\\private'), upload_to='identity_documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name="Fichier (pièce d'identité, recto)"),
        ),
    ]
