# Generated by Django 5.2.16 on 2026-08-06 23:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_seed_categories_and_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='max_guests',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Capacité max (personnes)'),
        ),
    ]
