# Generated by Django 5.2.16 on 2026-08-06 23:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_property_max_guests'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='pricing_period',
            field=models.CharField(choices=[('NIGHTLY', 'Par nuit'), ('MONTHLY', 'Par mois')], default='NIGHTLY', max_length=10, verbose_name='Type de location'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Prix'),
        ),
    ]
