# Generated by Django 5.2.16 on 2026-09-02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_property_pricing_period_alter_property_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='commission_percentage_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pourcentage retenu par KYI IMMOBILIER sur ce logement. Laissez vide pour utiliser le pourcentage par défaut de la plateforme.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Pourcentage commission (personnalisé)'),
        ),
    ]
