# Generated by Django 5.2.16 on 2026-07-15 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('icon', models.CharField(default='check', help_text="Name of the Lucide icon to display (e.g., 'wifi', 'wind', 'tv')", max_length=30)),
            ],
            options={
                'verbose_name': 'Équipement',
                'verbose_name_plural': 'Équipements',
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='properties/')),
                ('is_main', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Image du logement',
                'verbose_name_plural': 'Images du logement',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name="Titre de l'annonce")),
                ('description', models.TextField(verbose_name='Description détaillée')),
                ('property_type', models.CharField(choices=[('apartment', 'Appartement'), ('villa', 'Villa'), ('studio', 'Studio'), ('room', "Chambre d'hôte")], default='apartment', max_length=20, verbose_name='Type de logement')),
                ('price_per_night', models.DecimalField(decimal_places=0, max_digits=12, max_length=12, verbose_name='Prix par nuit (FCFA)')),
                ('address', models.CharField(max_length=255, verbose_name='Adresse')),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('neighborhood', models.CharField(max_length=100, verbose_name='Quartier')),
                ('latitude', models.FloatField(default=14.7167, verbose_name='Latitude')),
                ('longitude', models.FloatField(default=-17.4677, verbose_name='Longitude')),
                ('capacity', models.PositiveIntegerField(default=2, verbose_name='Capacité (personnes)')),
                ('bedrooms', models.PositiveIntegerField(default=1, verbose_name='Nombre de chambres')),
                ('bathrooms', models.PositiveIntegerField(default=1, verbose_name='Nombre de salles de bain')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible à la location')),
                ('status', models.CharField(choices=[('pending', 'En attente de validation'), ('approved', 'Publié'), ('rejected', 'Rejeté')], default='pending', max_length=15, verbose_name='Statut de validation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amenities', models.ManyToManyField(blank=True, related_name='properties', to='properties.amenity', verbose_name='Équipements')),
            ],
            options={
                'verbose_name': 'Logement',
                'verbose_name_plural': 'Logements',
                'ordering': ['-created_at'],
            },
        ),
    ]
