# Generated by Django 5.2.16 on 2026-07-21 00:58

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('reservations', '0002_alter_reservation_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commission',
            options={'ordering': ['-created_at'], 'verbose_name': 'Commission DEKOUWAY', 'verbose_name_plural': 'Commissions DEKOUWAY'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-created_at'], 'verbose_name': 'Facture', 'verbose_name_plural': 'Factures'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Paiement Entrant', 'verbose_name_plural': 'Paiements Entrants'},
        ),
        migrations.AlterModelOptions(
            name='paymenthistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Historique de Paiement', 'verbose_name_plural': 'Historiques de Paiements'},
        ),
        migrations.AlterModelOptions(
            name='payout',
            options={'ordering': ['-created_at'], 'verbose_name': 'Reversement Propriétaire', 'verbose_name_plural': 'Reversements Propriétaires'},
        ),
        migrations.AlterModelOptions(
            name='refund',
            options={'ordering': ['-created_at'], 'verbose_name': 'Remboursement', 'verbose_name_plural': 'Remboursements'},
        ),
        migrations.AlterField(
            model_name='commission',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Montant de la commission'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='created_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de création'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID unique (UUID)'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Est supprimé (Soft Delete)'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='commission', to='payments.payment', verbose_name='Paiement associé'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='percentage_applied',
            field=models.DecimalField(decimal_places=2, help_text='ex: 15.00 pour 15%', max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Pourcentage appliqué (%)'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='service_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Frais de service (Fixe)'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date de dernière modification'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Mis à jour par'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='updated_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de modification'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de création'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='file',
            field=models.FileField(upload_to='invoices/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Fichier Facture (PDF)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID unique (UUID)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Numéro de facture'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Est supprimé (Soft Delete)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='reservations.reservation', verbose_name='Réservation'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date de dernière modification'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Mis à jour par'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='updated_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de modification'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de création'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='XOF', max_length=3, verbose_name='Devise'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='error_message',
            field=models.TextField(blank=True, verbose_name="Message d'erreur"),
        ),
        migrations.AlterField(
            model_name='payment',
            name='gateway_transaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='ID Transaction (Gateway)'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID unique (UUID)'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Est supprimé (Soft Delete)'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('WAVE', 'Wave'), ('ORANGE_MONEY', 'Orange Money'), ('CREDIT_CARD', 'Carte Bancaire'), ('BANK_TRANSFER', 'Virement Bancaire')], max_length=20, verbose_name='Méthode de paiement'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='reservations.reservation', verbose_name='Réservation'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('SUCCESS', 'Réussi'), ('FAILED', 'Échoué'), ('REFUNDED', 'Remboursé')], db_index=True, default='PENDING', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date de dernière modification'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Mis à jour par'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='updated_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de modification'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments_made', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='created_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de création'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='details',
            field=models.JSONField(default=dict, verbose_name='Détails'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID unique (UUID)'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Est supprimé (Soft Delete)'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='new_status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('SUCCESS', 'Réussi'), ('FAILED', 'Échoué'), ('REFUNDED', 'Remboursé')], max_length=20, verbose_name='Nouveau statut'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='old_status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('SUCCESS', 'Réussi'), ('FAILED', 'Échoué'), ('REFUNDED', 'Remboursé')], max_length=20, verbose_name='Ancien statut'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='payments.payment', verbose_name='Paiement'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date de dernière modification'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Mis à jour par'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='updated_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de modification'),
        ),
        migrations.AlterField(
            model_name='payout',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Montant reversé'),
        ),
        migrations.AlterField(
            model_name='payout',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='payout',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='payout',
            name='created_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de création'),
        ),
        migrations.AlterField(
            model_name='payout',
            name='currency',
            field=models.CharField(default='XOF', max_length=3, verbose_name='Devise'),
        ),
        migrations.AlterField(
            model_name='payout',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression'),
        ),
        migrations.AlterField(
            model_name='payout',
            name='gateway_transaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='ID Transaction Reversement'),
        ),
        migrations.AlterField(
            model_name='payout',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID unique (UUID)'),
        ),
        migrations.AlterField(
            model_name='payout',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Est supprimé (Soft Delete)'),
        ),
        migrations.AlterField(
            model_name='payout',
            name='method',
            field=models.CharField(choices=[('WAVE', 'Wave'), ('ORANGE_MONEY', 'Orange Money'), ('CREDIT_CARD', 'Carte Bancaire'), ('BANK_TRANSFER', 'Virement Bancaire')], max_length=20, verbose_name='Méthode de reversement'),
        ),
        migrations.AlterField(
            model_name='payout',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts_received', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire'),
        ),
        migrations.AlterField(
            model_name='payout',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='reservations.reservation', verbose_name='Réservation'),
        ),
        migrations.AlterField(
            model_name='payout',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente de reversement'), ('PROCESSING', 'En cours de traitement'), ('COMPLETED', 'Versé'), ('FAILED', 'Échec')], db_index=True, default='PENDING', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='payout',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date de dernière modification'),
        ),
        migrations.AlterField(
            model_name='payout',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Mis à jour par'),
        ),
        migrations.AlterField(
            model_name='payout',
            name='updated_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de modification'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='created_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de création'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='gateway_transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID Transaction (Gateway)'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID unique (UUID)'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Est supprimé (Soft Delete)'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='payments.payment', verbose_name="Paiement d'origine"),
        ),
        migrations.AlterField(
            model_name='refund',
            name='reason',
            field=models.TextField(verbose_name='Motif du remboursement'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('SUCCESS', 'Réussi'), ('FAILED', 'Échoué'), ('REFUNDED', 'Remboursé')], default='PENDING', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date de dernière modification'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Mis à jour par'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='updated_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de modification'),
        ),
    ]
