# Generated by Django 5.2.16 on 2026-07-26 10:07

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_commission_options_alter_invoice_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID unique (UUID)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date de dernière modification')),
                ('created_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de création')),
                ('updated_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de modification')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Est supprimé (Soft Delete)')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Commission Propriétaire (%)')),
                ('client_service_fee', models.DecimalField(decimal_places=2, default=Decimal('5000.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Frais de service Client (Fixe en FCFA)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Mis à jour par')),
            ],
            options={
                'verbose_name': 'Configuration de la Plateforme',
                'verbose_name_plural': 'Configuration de la Plateforme',
                'db_table': 'payments_platform_settings',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
