# Generated by Django 5.2.16 on 2026-08-06 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_platformsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='branding/', verbose_name="Image Hero (page d'accueil)"),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='branding/', verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='site_name',
            field=models.CharField(default='DEKOUWAY', max_length=100, verbose_name='Nom du site'),
        ),
    ]
