# Generated by Django 5.2.16 on 2026-09-02

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_platformsettings_hero_image_platformsettings_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformsettings',
            name='commission_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Commission Propriétaire (%)'),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='site_name',
            field=models.CharField(default='KYI IMMOBILIER', max_length=100, verbose_name='Nom du site'),
        ),
    ]
