# Generated by Django 5.2.16 on 2026-09-13 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_commission_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commission',
            options={'ordering': ['-created_at'], 'verbose_name': 'Commission KYI IMMOBILIER', 'verbose_name_plural': 'Commissions KYI IMMOBILIER'},
        ),
    ]
