# Generated by Django 5.2.16 on 2026-09-14 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_seed_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='is_flagged',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Signalé par la modération IA'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='moderation_reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='Motif du signalement'),
        ),
        migrations.AddField(
            model_name='ticketmessage',
            name='is_flagged',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Signalé par la modération IA'),
        ),
        migrations.AddField(
            model_name='ticketmessage',
            name='moderation_reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='Motif du signalement'),
        ),
    ]
