# Generated by Django 5.2.16 on 2026-07-22 19:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID unique (UUID)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date de dernière modification')),
                ('created_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de création')),
                ('updated_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de modification')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Est supprimé (Soft Delete)')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('feature', models.CharField(max_length=50, verbose_name='Fonctionnalité IA')),
                ('model_name', models.CharField(max_length=100, verbose_name='Modèle utilisé')),
                ('prompt_tokens', models.PositiveIntegerField(default=0, verbose_name='Jetons Prompt')),
                ('completion_tokens', models.PositiveIntegerField(default=0, verbose_name='Jetons Génération')),
                ('total_tokens', models.PositiveIntegerField(default=0, verbose_name='Total Jetons')),
                ('execution_time_sec', models.FloatField(default=0.0, verbose_name="Temps d'exécution (s)")),
                ('is_success', models.BooleanField(default=True, verbose_name='Succès')),
                ('fallback_used', models.BooleanField(default=False, verbose_name='Moteur de secours utilisé')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Mis à jour par')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Journal d'Usage IA",
                'verbose_name_plural': "Journaux d'Usage IA",
                'db_table': 'ai_usage_log',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID unique (UUID)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date de dernière modification')),
                ('created_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de création')),
                ('updated_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de modification')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Est supprimé (Soft Delete)')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('mode', models.CharField(choices=[('GENERAL_CHAT', 'Discussion Générale'), ('CLIENT_ASSISTANT', 'Assistant Client'), ('OWNER_ASSISTANT', 'Assistant Propriétaire'), ('ERP_ADMIN_ASSISTANT', 'Assistant SuperAdmin ERP'), ('RECOMMENDATION', 'Moteur de Recommandation'), ('MODERATION', 'Modération de Contenu'), ('DESCRIPTION_GEN', 'Génération de Description')], default='GENERAL_CHAT', max_length=30, verbose_name='Mode IA')),
                ('title', models.CharField(default='Nouvelle conversation', max_length=255, verbose_name='Titre de la conversation')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Mis à jour par')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Conversation IA',
                'verbose_name_plural': 'Conversations IA',
                'db_table': 'ai_conversation',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID unique (UUID)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date de dernière modification')),
                ('created_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de création')),
                ('updated_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de modification')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Est supprimé (Soft Delete)')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('role', models.CharField(choices=[('SYSTEM', 'Système'), ('USER', 'Utilisateur'), ('ASSISTANT', 'Assistant IA')], max_length=20, verbose_name='Rôle')),
                ('content', models.TextField(verbose_name='Contenu du message')),
                ('tokens_used', models.PositiveIntegerField(default=0, verbose_name='Nombre de jetons')),
                ('latency_ms', models.FloatField(default=0.0, verbose_name='Durée (ms)')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai.conversation', verbose_name='Conversation')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Mis à jour par')),
            ],
            options={
                'verbose_name': 'Message IA',
                'verbose_name_plural': 'Messages IA',
                'db_table': 'ai_conversation_message',
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
    ]
