# Generated by Django 5.2.16 on 2026-07-15 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField(verbose_name="Date d'arrivée")),
                ('check_out', models.DateField(verbose_name='Date de départ')),
                ('total_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Prix total (FCFA)')),
                ('status', models.CharField(choices=[('pending', 'En attente de validation'), ('approved', 'Acceptée (En attente de paiement)'), ('confirmed', 'Confirmée (Payée)'), ('rejected', 'Refusée'), ('cancelled', 'Annulée')], default='pending', max_length=20, verbose_name='Statut de la réservation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['-created_at'],
            },
        ),
    ]
