# Generated by Django 5.2.16 on 2026-07-21 00:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AlterModelOptions(
            name='notificationhistory',
            options={'ordering': ['-created_at'], 'verbose_name': "Historique d'envoi de Notification", 'verbose_name_plural': "Historiques d'envoi de Notifications"},
        ),
        migrations.AlterModelOptions(
            name='notificationpreference',
            options={'ordering': ['-created_at'], 'verbose_name': 'Préférence de Notification', 'verbose_name_plural': 'Préférences de Notifications'},
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de création'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID unique (UUID)'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Est supprimé (Soft Delete)'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Est lu'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Lien de redirection'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de lecture'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date de dernière modification'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Mis à jour par'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='updated_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de modification'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='notificationhistory',
            name='channel',
            field=models.CharField(max_length=50, verbose_name="Canal d'envoi"),
        ),
        migrations.AlterField(
            model_name='notificationhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='notificationhistory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='notificationhistory',
            name='created_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de création'),
        ),
        migrations.AlterField(
            model_name='notificationhistory',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression'),
        ),
        migrations.AlterField(
            model_name='notificationhistory',
            name='error_message',
            field=models.TextField(blank=True, verbose_name="Message d'erreur (si échec)"),
        ),
        migrations.AlterField(
            model_name='notificationhistory',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID unique (UUID)'),
        ),
        migrations.AlterField(
            model_name='notificationhistory',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Est supprimé (Soft Delete)'),
        ),
        migrations.AlterField(
            model_name='notificationhistory',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='notifications.notification', verbose_name="Notification d'origine"),
        ),
        migrations.AlterField(
            model_name='notificationhistory',
            name='status',
            field=models.CharField(max_length=50, verbose_name="Statut de l'envoi"),
        ),
        migrations.AlterField(
            model_name='notificationhistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date de dernière modification'),
        ),
        migrations.AlterField(
            model_name='notificationhistory',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Mis à jour par'),
        ),
        migrations.AlterField(
            model_name='notificationhistory',
            name='updated_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de modification'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='created_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de création'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='email_enabled',
            field=models.BooleanField(default=True, verbose_name='Activer Email'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID unique (UUID)'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Est supprimé (Soft Delete)'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='push_enabled',
            field=models.BooleanField(default=True, verbose_name='Activer Push (In-App)'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='sms_enabled',
            field=models.BooleanField(default=False, verbose_name='Activer SMS'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date de dernière modification'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Mis à jour par'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='updated_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de modification'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
    ]
